apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-helm-with-argo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Kapil-Bhalodiya/helm-with-argocd.git
    targetRevision: HEAD
    path: webapp1
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true